### ISSUE TITLE
Max number of commands ?

### ISSUE THREAD

**Issue by Darynh** [steelbrain/node-ssh#10]
Heyho !

I'm running into an issue with the module.
I'm trying to run an exec command in a callback of another function. I'm checking if the connection is done beforehand then run the command.
In total, i'm doing two commands per data, which is 2 * 25 commands, first being an exec "find" and second a get file.
However, it seems that what ever I try, the exec command will always stop after 20 calls.
Any idea where to look ?
Cheers,

EDIT:

I tried with the following code, it stops after 20 commands:

```js
var node_ssh = require('node-ssh');
var connectAttr = require('./connectionAttr');

var ssh = new node_ssh(connectAttr);

ssh.connect().then(function () {
    for (var i = 1; i < 30; i++) {
        ssh.exec('echo ' + i).then(function (std) {
            console.log(std.stdout);
        });
    }
});
```

**Comment by Darynh** [comment]
Seems like it's a problem with concurrent commands which is limited to 20 (https://github.com/mscdex/ssh2/issues/222). Sorry about that !

**Comment by steelbrain** [comment]
Yep. ssh.exec is a non-blocking async operation, So executing stuff in a loop like that would make it co-current.

**Comment by niklasravnsborg** [comment]
@Darynh I have a similar Problem with `put`. Did you solve it? I get `{ [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }`

**Comment by steelbrain** [comment]
@niklasravnsborg It's actually a won't fix, because you should not execute a lot of commands cocurrently, You should wait for the previous ones to be executed first, or maybe implement some sort of throttling.
Also https://github.com/mscdex/ssh2 handles the command execution and stuff, `node-ssh` just provides a Nice API over it.

**Comment by niklasravnsborg** [comment]
@steelbrain Hmm, so I have to run them one by one, right? Thats exactly what I intended with my code.

```
var NodeSSH = require('node-ssh'),
    config  = require('./deploy_info.json');

var ssh = new NodeSSH({
  host:     config.host,
  username: config.username,
  password: config.password
});

uploadList = [
	// at least 12 elements in here
	'file01.foo',
	'file02.foo',
	'file03.foo',
	'file04.foo',
	'file05.foo',
	'file06.foo',
	'file07.foo',
	'file08.foo',
	'file09.foo',
	'file10.foo',
	'file11.foo'
];

ssh.connect().then(function() {
	uploadList.reduce(function(sequence, file, index) {

		// appends these then functions to sequence
		return sequence.then(function() {

			var uploadSrc = 'local/path/'  + file,
			    uploadTo  = 'remote/path/' + file;

			console.log('Uploading', file);
			return ssh.put(uploadSrc, uploadTo).then(function() {
				console.log('finished');
			});

		});

	}, Promise.resolve()).then(function() {
		console.log('done');
	}, function(err) {
		console.error(err);
	});
});
```

Should do it from my perspective. It appends a buch of thens together and then runs them. Every then callback `ssh.put`'s one file. I'll look at promise sequencing again.

**Comment by steelbrain** [comment]
You are using the put method super-inefficiently, You should use the putMulti method, or request the SFTP instance and pass it to the put method, 'cause otherwise, it'll request a different SFTP instance for each put.

**Comment by niklasravnsborg** [comment]
Awesome, did it! Thank you very much :relaxed:.

**For those who are interested:**
``` javascript

var NodeSSH = require('node-ssh'),
    config  = require('./deploy_info.json');

var ssh = new NodeSSH({
    host:     config.host,
    username: config.username,
    password: config.password
});

uploadList = [
    // at least 12 elements in here
    'file01.foo',
    'file02.foo',
    'file03.foo',
    'file04.foo',
    'file05.foo',
    'file06.foo',
    'file07.foo',
    'file08.foo',
    'file09.foo',
    'file10.foo',
    'file11.foo'
];

ssh.connect().then(function() {
    ssh.requestSFTP().then(function(sftp) {
        uploadList.reduce(function(sequence, file, index) {

            // appends these then functions to sequence
            return sequence.then(function() {

                var uploadSrc = 'local/path/'  + file,
                    uploadTo  = 'remote/path/' + file;

                console.log('Uploading', file);
                
                // !!! important: pass the sftp object here !!!
                return ssh.put(uploadSrc, uploadTo, sftp).then(function() {
                    console.log('finished');
                });

            });

        }, Promise.resolve()).then(function() {
            console.log('done');
        }, function(err) {
            console.error(err);
        });
    });
});
```
