### ISSUE TITLE
option to kill exec or send asynchron stdin

### ISSUE THREAD

**Issue by vpfautz** [steelbrain/node-ssh#100]
Is it possible to kill a exec command or send asynchron stdin without closing the ssh connection?
My workaround is to let the executed program print its pid. So I can later `exec(kill, pid)`. Is there better way?

**Comment by steelbrain** [comment]
This is a limitation of the promises API. It does not allow anything other than `then` and `catch`.

You can still use the tricks of the `ssh2` API though. An `ssh2` instance is available at `ssh.connection` after login, for example: https://stackoverflow.com/questions/22164570/sending-a-terminate-ctrlc-command-in-node-js-ssh2

**Comment by cinderblock** [comment]
I've been wanting this feature as well. I made a quick stab at implementing this. Checkout #125

**Comment by steelbrain** [comment]
Should be handled by https://github.com/steelbrain/node-ssh/pull/297

**Comment by steelbrain** [comment]
Released in v9.0.0

**Comment by dudu631** [comment]
@steelbrain just to make sure, how would you handle killing the async process?
