### ISSUE TITLE
Fails with no error on windows 7 system

### ISSUE THREAD

**Issue by trezero** [steelbrain/node-ssh#101]
Trying to figure out how to diagnose this further. I have a connection as shown below. On OSX, Windows 7 64 bit and a Windows 10 system this connection works with no problems. However on 1 Windows 7 64 bit system the application never even displays the first log.info command (FIRST SSH RESULT ---).  My understanding was that even if there was an error connecting I would at least get this far. Is there some other error handeling I'm missing? Is there any other items that need to be installed on a windows 7 system before this can work properly? If I could at least find a way to see an error that would be very helpful.

```
let ssh = new node_ssh();
  ssh.connect({
    host: deviceIP,
    username: 'myuser',
    password: 'mypass',
    agent: 'pageant',
  }).then(function () {
    ssh.execCommand(command, {cwd: '/var/www'}).then(function (result) {
      log.info('FIRST SSH RESULT ---');
      log.info('STDOUT: ' + result.stdout);
      log.info('STDERR: ' + result.stderr);
    });
  });
```

Edit by @steelbrain: Fix formatting

**Comment by steelbrain** [comment]
Hi @trezero 

If it does not invoke `then`, then it means the promise was rejected, in which case the `catch` handler is invoked.

Can you try this and see what you get?
```
ssh.execCommand(command, { cwd: '/var/www' }).then(function(result) {
  console.log('result', result)
}).catch(function(error) {
  console.error('it didnt work', error)
})
```

Tip: You don't have to nest `.then`s, you can chain promises like

```
ssh.connect(...)
  .then(function() {
    return ssh.execCommand(...)
  })
  .then(function(result) {
    console.log('result', result)
  })
  .catch(function(error) {
    console.error('oops', error)
  })
```

**Comment by steelbrain** [comment]
Closing as no response received from OP in over two years. Feel free to continue discussing
