### ISSUE TITLE
Promise put doesn't get fulfilled if new directories have to be created

### ISSUE THREAD

**Issue by niklasravnsborg** [steelbrain/node-ssh#11]
Hey @steelbrain, awesome repo! I have spottet a annoying bug – or maybe I'm doing it wrong? Try this code and make sure that the `remote/path/to/file.file` doesn't exist, so that `node-ssh` has to create those dirs. When I run the code then, my script stops and Node is stuck. But weirdly the remote directories get created and the file gets uploaded. So I have to force stop the script and restart it. After the restart it proceeds to the other files as expected until it has to create directories again. Do you have an idea for that problem? 

This looks a little bit similar to https://github.com/steelbrain/node-ssh/issues/4. 

```javascript
var NodeSSH = require('node-ssh'),
    config  = require('./deploy_info.json');

var ssh = new NodeSSH({
  host:     config.host,
  username: config.username,
  password: config.password
});

ssh.connect().then(function() {
  ssh.put('local/path/to/file.file', 'remote/path/to/file.file').then(function() {
    ssh.end();
  }, function(err) {
    console.error(err);
  });
});
```

**Comment by steelbrain** [comment]
It used to work like a month or two ago, I'll investigate.

**Comment by steelbrain** [comment]
Yep, I am able to repro

**Comment by niklasravnsborg** [comment]
Awesome! Thanks for the quick response :+1:
