### ISSUE TITLE
Promise Rejected - All configured authentication methods failed

### ISSUE THREAD

**Issue by phinelipy** [steelbrain/node-ssh#115]
The whole task is to stop an aws instance from backend and then restarting the same, once the instance is running, I need to run few commands after connecting through ssh.
I am getting the instance status as "Running" as well.
I tried to access the same instance from Putty, I got error message saying "Disconnected: No supported authentication methods available(server sent: publickey)".

This is my code where I am trying to connect to an instance:-

console.log("instance status: ", status)
ssh.connect({
host: publicIp,
username: '*',
readyTimeout: 99999,
privateKey: '.pem'
}).then(function(result) {
console.log("result: ", result);
});

Error:
instance status: running
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: All configured authentication methods failed
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

note: For the first time, this was working.

Can anyone tell me what am I doing wrong here?

**Comment by phinelipy** [comment]
The whole task is to stop an aws instance from backend and then restarting the same, once the instance is running, I need to run few commands after connecting through ssh.
I am getting the instance status as "Running" as well.

This is my code where I am trying to connect to an instance:-

console.log("instance status: ", status)
ssh.connect({
	host: publicIp,
	username: '****',
	readyTimeout: 99999,
	privateKey: '***.pem'
}).then(function(result) {
	console.log("result: ", result);
});

Error:
instance status:  running
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: All configured authentication methods failed
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by steelbrain** [comment]
Hi @phinelipy

The error log is being produced from your own code. You have to add a [`.catch()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) handler to your promise chain.

The error message itself indicates that all configured authentication methods, failed. Which they would be 'cause the private key path you're feeding it is `.pem` which is not valid. You have to give it exact or at least relative path on the file system where the private key exists.

Furthermore this is a general javascript question and is not related to this repository so am closing it as external. Feel free to continue discussing
