### ISSUE TITLE
getFile documentation is confused

### ISSUE THREAD

**Issue by marianomoretti** [steelbrain/node-ssh#116]
Hey! :)

I would like to ask what returns the `getFile` method. I mean, I'm sure that returns a promise. But in some parts of the documentation says that returns a void promise: 
`getFile(localFile: string, remoteFile: string, sftp: ?Object = null, opts: ?Object = null): Promise<void>`
in other part say that return the content:
`ssh.getFile('/home/steel/Lab/localPath', '/home/steel/Lab/remotePath').then(function(Contents) {`
and in your tests you are checking if the file exists:
`await client.getFile(targetFile, sourceFile)`
`expect(await exists(targetFile)).toBe(true)`
Maybe,  the promise is solved with the content and also the file is created, but is not clear for me and i want to be sure of that. Let me know if I wasn't clear :)

Thanks!

**Comment by steelbrain** [comment]
Hey! 

Sorry for the confusion, the first parameter is where you want to save it, the second parameter is where you want to download from. The third parameter is optional and is the return value of `ssh.requestSFTP`, you probably don't want to specify the last one

Let me know if I can explain this further.
Cheers

**Comment by marianomoretti** [comment]
Hey! 
And when the promise is solved, what data it's passed? The downloaded data or the file name?
Thanks!

**Comment by marianomoretti** [comment]
Ok, Thanks! I will close this issue. :)
