### ISSUE TITLE
TypeError: a.forEach is not a function

### ISSUE THREAD

**Issue by liorko87** [steelbrain/node-ssh#117]
Hello,

I'm trying to execute some executable on remote machine and leave the executable to run in the background.
When I'm executing it using `exec` I got this error:
` Error: TypeError: a.forEach is not a function`

This is what I tried:
```
let sshClient = new ssh();
    sshClient.connect({
        host: '34.239.19.87',
        username: 'ubuntu',
        privateKey: '/home/user/key.pem'}).
    then(function () {
        let command = './cct_proxy -i ' + partyId + ' -c ' +
        numberOfParties + ' -f parties.conf -l 700 -p ' + portNumber + ' &';
        sshClient.exec(command, {cwd:'/home/ubuntu/ACP/cct_proxy',
            options: { pty: true } }).
        then(function (result) {
            console.log('STDOUT: ' + result.stdout);
            console.log('STDERR: ' + result.stderr);
        }).catch(function (error) {
            console.log('Error: ' + error);
        });
    }).
    catch(function (error) {
      console.log('Error: ' + error);
    });
```

**Comment by steelbrain** [comment]
Hi @liorbiu 

Can you please provide a full stack trace of the error?

**Comment by liorbiu** [comment]
Hi @steelbrain 

This is the only line I can see in the stack trace. The execption thrown from the `_asyncToGenerator` function.

I'm attaching my function here

```
let sshClient = new ssh();
    sshClient.connect({
        host: 'my_host',
        username: 'mu_user',
        privateKey: 'my_ket'}).
    then(function () {
        let command = './cct_proxy -i ' + partyId + ' -c ' +
        numberOfParties + ' -f parties.conf -l 700 -p ' + portNumber + ' &';
        sshClient.exec(command, {cwd:'/home/ubuntu/ACP/cct_proxy',
            options: { pty: true } }).
        then(function (result) {
            console.log('STDOUT: ' + result.stdout);
            console.log('STDERR: ' + result.stderr);
        }).catch(function (error) {
            console.log('Error: ' + error);
        });
    }).
    catch(function (error) {
      console.log('Error: ' + error);
    });
```

**Comment by cinderblock** [comment]
I ran into this bug as well. The issue here is that `exec()`'s second argument (the arguments to be passed to the command) are not optional.

@liorko87 You simply need to specify an empty array of "parameters" (aka arguments) as the second argument to `exec()`:

```javascript
sshClient.exec(command, [], {cwd:'/home/ubuntu/ACP/cct_proxy',
            options: { pty: true } })
```

At a minimum, it would be nice if the error was a little more descriptive of the problem. However I think it would be easier to simply make the second argument to exec optional.

**Comment by Malvineous** [comment]
Just ran into this too, but in my case I accidentally used `exec()` when I meant to use `execCommand()`.

**Comment by steelbrain** [comment]
Closing based on above answer. Feel free to continue discussing
