### ISSUE TITLE
Use in the Browser

### ISSUE THREAD

**Issue by OrangeDrangon** [steelbrain/node-ssh#123]
Is it possible to use this in the browser using something like angular or just your every day vanilla js and webpack?

I try not to use these issues as tech support but didn't really know where else to look

**Comment by steelbrain** [comment]
It is highly unlikely that this would work in the browser. Mainly because browsers only allow to establish connections of protocols they support like https, http, webrtc. Raw tcp/udp is not available without a websocket proxy :(
