### ISSUE TITLE
exit event is not available

### ISSUE THREAD

**Issue by antoniom** [steelbrain/node-ssh#126]
When trying the `exec` method via ssh2 there is available an `exit` event which has the following documentation

> An exit event may (the SSH2 spec says it is optional) be emitted when the process finishes. If the process finished normally, the process's return value is passed to the exit callback. If the process was interrupted by a signal, the following are passed to the exit callback: null, < string >signalName, < boolean >didCoreDump, < string >description.

For example:
```
var Client = require('ssh2').Client;
 
var conn = new Client();
conn.on('ready', function() {
  conn.exec('ls -la', function(err, stream) {
    if (err) throw err;
    stream.on('exit', function(code, signal) {
      console.log('EXITED');
    });
    stream.on('data', function(data) {
      console.log(data.toString());
    });
    stream.on('close', function(code, signal) {
      conn.end();
    });
  });
}).connect({...});
```
However, this `exit` event is not exposed via node-ssh either on `exec` or `execCommand` method.

Is this done intentionally?
Are there any plans to implement this?

**Comment by steelbrain** [comment]
Hi

Unlike ssh2, you don't have to listen to the streams directly in `node-ssh`. It listens on the `close` (similar to `exit`) for you itself [here](https://github.com/steelbrain/node-ssh/blob/b02e8088f287f3ee2697f67ab94ec9fc4579f309/src/index.js#L167). 

If you would like to perform something on the ssh2 instance directly, you can access it via `.connection` on the node-ssh instance

**Comment by antoniom** [comment]
Thanks!

I was ready to use `.connection` you refered but then I realized that `exec` or `execCommand` resolves everytime the command end its execution.

**Comment by dandanknight** [comment]
Hi, related question. When performing an `exec`, is it possible to access the exit code? The resolved promise for me only seems to contain the stdout.

**Comment by steelbrain** [comment]
Hi @dandanknight 

If the `stream` is not specified, you get an object return value with `code` inside

**Comment by dandanknight** [comment]
@steelbrain Thanks for the quick reply, I'll give it a go. I'm using the `onStdout` stream though, but may be able to do without it
