### ISSUE TITLE
failed to upload a directory  to server

### ISSUE THREAD

**Issue by JerryMissTom** [steelbrain/node-ssh#127]
Hi, thanks for this great job. And I meet a trouble when upload a directory  to server. I build a vue project ,the final directory is below 
```
-- smartbuilding
     --static
        --js
        --img
     --index.html
```
I want to upload this directory to my server, the code is below:
```
node_ssh = require('node-ssh');
ssh = new node_ssh();
ssh.connect({
    host: '',
    username: '',
    port: ,
    password: '',
    readyTimeout: 5000
}).then(function () {
    ssh.putDirectory(process.cwd() + '/smartbuilding', '/home/building').then(function () {
        console.log("The File thing is done");
        ssh.dispose();
    }, function (error) {
        console.log("Something's wrong");
        console.log(error);
        ssh.dispose();
    })
});
```
Only file `index.html` upload successfully. I don't know how to debug. could you please tell how to upload a directory with files and subdirectory  to  a server. I will be grateful If you can show me the code,

**Comment by JerryMissTom** [comment]
And I try just upload a file to the server, the code is below:
```
node_ssh = require('node-ssh');
ssh = new node_ssh();
ssh.connect({
    host: '',
    username: '',
    port:,
    password: '',
    readyTimeout: 5000
}).then(function () {
    ssh. putFile(process.cwd() + '/index.html', '/home/building').then(function () {
        console.log("The File thing is done");
        ssh.dispose();
    }, function (error) {
        console.log("Something's wrong");
        console.log(error);
        ssh.dispose();
    })
});
```
It fails, the error info is below
<img width="757" alt="default" src="https://user-images.githubusercontent.com/15966403/48703011-7414be00-ec2d-11e8-91b5-0e2717551e06.png">

**Comment by capnajax** [comment]
I just ran into the putFile issue -- worked around it by specifying the complete file name in the remote path, not just the directory to put it in.

**Comment by JerryMissTom** [comment]
@capnajax  really? that's great. Look forward to this.

**Comment by paragraff** [comment]
@JerryMissTom I set the concurrency option to 1 in for omitting this error:

```js
...
ssh.putDirectory(process.cwd() + '/smartbuilding', '/home/building', {concurrency: 1}).then(...)
...
```

**Comment by steelbrain** [comment]
Default concurrency now is `1`
