### ISSUE TITLE
Way to determine if connected?

### ISSUE THREAD

**Issue by worksofliam** [steelbrain/node-ssh#128]
Hi!

I see there is no API to determine whether the client is connected to a remote server.

Is there a correct way to do it with this API?

Thanks!

**Comment by WorksOfLiam** [comment]
This is what I am doing right now.

```
  isConnected: function() {
    if (client === undefined) {
      return false;
    } else {
      if (client.connection === null) {
        return false;
      } else {
        return true;
      }
    }
  }
```

**Comment by kaeside** [comment]
@WorksOfLiam Wouldn't the following be simpler since validating the connection is based on whether the function returns true?

`isConnected: function() {
    if (client === undefined || client.connection === null) {
      return false;
    } else {
        return true;
      }
    }`

**Comment by brianxautumn** [comment]
Is there a disconnected event?

**Comment by steelbrain** [comment]
@brianxautumn Right now you could do `ssh.connection.on('end', ...)`, not super-pretty but works well

**Comment by steelbrain** [comment]
Re OP: v10 includes a new `isConnected()` method so closing this issue
