### ISSUE TITLE
File resume is currently not supported

### ISSUE THREAD

**Issue by joneldiablo** [steelbrain/node-ssh#131]
Hi, I'm having this error sometimes: "File resume is currently not supported". I have a recursive function which use ssh.putFile while upload many files:

```
const bubble = (track, i) => {
  let dir = sourceDirectoryName + '/' + newtrackname, resourcesDirectory + '/' + newtrackname;
  ssh.putFile(dir, fastPut)
    .then(function (success) {
          if ((i+1) < length) {
            i++;
            setTimeout(() => bubble(result[i], i), 100);
          }
    });
}
bubble(track[0],0);
```

**Comment by steelbrain** [comment]
Hi @joneldiablo

`node-ssh` is a wrapper around the awesome ssh2 lib (https://github.com/mscdex/ssh2), please see if you what you're looking for is supported in that lib directly. If it's not, I am afraid there's not much I can do from here :)

**Comment by steelbrain** [comment]
Closing as external: https://github.com/mscdex/ssh2-streams/issues/118

Feel free to continue discussing
