### ISSUE TITLE
Error when using put and create directories

### ISSUE THREAD

**Issue by niklasravnsborg** [steelbrain/node-ssh#14]
```js
NodeSSH = require('node-ssh');

var ssh = new NodeSSH();

ssh.connect({
    host: 'host',
    username: 'user',
    password: 'pass'
}).then(function() {
    return ssh.put('dist/index.html', 'foo/index.html').then(function() {
        console.log('done');
    });
}).catch(function(err) {
    console.error(err);
});
```

Note that I'm uploading to an non-existent directory. I remember in v1.0.0 this directory got created automatically. But when I run the above script I get `Fatal error: Cannot read property 'mkdir' of undefined` again.

**Comment by steelbrain** [comment]
I really feel the need of a unit test, sorry man, my bad.

**Comment by niklasravnsborg** [comment]
No problem. I'm your unit test!
