### ISSUE TITLE
Upload only newer files?

### ISSUE THREAD

**Issue by sphela02** [steelbrain/node-ssh#146]
Is there any way to only upload newer files from local to remote?

I realize it's not in the standard docs, but maybe there's a pathway to get there.

Maybe "stat" the remote file to get dates?

Any tips would be appreciated.

Thanks!
Sean P

**Comment by steelbrain** [comment]
Thank you for the request. Implementing this function in the library is out of scope as it's a relatively advanced feature. I would welcome a third party library implementing this.

**Comment by sphela02** [comment]
Thanks for answering!  I forgot about this question.  We have been using node-ssh for a staging preparation tool, it's working well for us.

**Comment by steelbrain** [comment]
Closing based on above comment, feel free to continue discussing
