### ISSUE TITLE
Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by mytee306** [steelbrain/node-ssh#149]
[Question](https://stackoverflow.com/questions/53400628/cannot-parse-privatekey-unsupported-key-format) may be related 

As well as this [issue](https://github.com/mscdex/ssh2-streams/issues/100)

**Comment by mytee306** [comment]
Solved by another [thread](https://serverfault.com/questions/939909/ssh-keygen-does-not-create-rsa-private-key/941893#941893?newreg=141e245aa38c4458a5551228ae101e66)

New keys with OpenSSH private key format can be converted using ssh-keygen utility to the old PEM format.

```sh
ssh-keygen -p -m PEM -f ~/.ssh/id_rsa
```

There is no need to downgrade to older OpenSSH just to achieve this result.

Props to [mydeardiary](https://serverfault.com/users/506882/mydeardiary)

**Comment by evansharp** [comment]
Backsliding the encryption chosen for the key hardly seems like a fix. Where upstream is the holdup adding Ed25519? Many projects are breaking as it gains adoption and more people are upgrading their keys.

**Comment by davidmoshal** [comment]
Not sure what the 'old format' vs any other format is, but for Ubuntu 20

`ssh-keygen -p -m PEM -f ~/.ssh/id_rsa`

seems to be a requirement.
