### ISSUE TITLE
Connections never closed

### ISSUE THREAD

**Issue by hagen** [steelbrain/node-ssh#158]
Hey there,
am running tests using `node-ssh`, and the test suite never ends because SSH connection never closes (inspected with `process._getActiveHandles()`). Does this have to be done manually? I thought no?
The use case is I'm opening ssh connections to a server multiple times for different requests. Each ssh session may execute a number of commands. Once done, I need to then close that connection. However, when I run `ssh.dispose()`, I get ECONNRESET errors.
```js
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
```
what am I doing wrong here?

Code sample:
```js
async ssh(creds, cmd) {
    let client = new SSH();
    let session = await client.connect(creds);
    let cmds = Array.isArray(cmd) ? cmd : [cmd];
    let results = await new Promise(function (resolve, reject) {
        mapSeries(
            cmds,
            async function exec(cmd) {
                let result = await session.execCommand(cmd);
                if (result.stderr) {
                    throw new Error(result.stderr);
                }
                return result.stdout;
            },
            async function done(err, results) {
                if (err) {
                    return reject(err);
                }
                resolve(results);
            }
        )
    });
    session.dispose();
    return results;
}
```

**Comment by hagen** [comment]
A reprex, if it helps:
```js
const SSH = require('node-ssh');
const creds = {
    host: process.env.HOST,
    username: process.env.SSH_USERNAME,
    password: process.env.SSH_PASSWORD
};
async function ssh() {
    let client = new SSH();
    await client.connect(creds);
    let cmd = `aws s3 cp s3://${process.env.S3_BUCKET}/path/to/object .`;
    let result = await client.execCommand(cmd);
    if (result.stderr.length) {
        throw new Error(result.stderr);
    }
    client.dispose();
    return result.stdout;
}
ssh().then(console.log).catch(console.error);
```
this code produces this error:
```js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
```

**Comment by hagen** [comment]
This is an OpenSSH-on-Windows issue. Not reproducible when SSHing to *nix from Node.

**Comment by timberlakegregg** [comment]
Were you able to identify the Windows OpenSSH issue that caused the dispose() method to throw this error? I hit the same error, and am also using an OpenSSH host with node-ssh. You're my first ray of hope after hours of debugging.

**Comment by hagen** [comment]
Sorry no. Instead, I just ignore connection closed errors in the `catch` or `reject` handler.

**Comment by coeing** [comment]
@hagen Could you reopen the issue? It happens in our application as well and only with Windows servers. Just ignoring the errors does not seem to be a clean solution ;)

**Comment by steelbrain** [comment]
@coeing Instead of re-opening this one, could you please create another? Steps for me to reproduce the error locally would be much appreciated

**Comment by coeing** [comment]
In my case I could not even catch the ECONNRESET error when calling ssh.dispose() because it happened afterwards. It seems like there is still some stream reading happening after the dispose which produces the error. Would it be possible to make sure that the SSH connection is completely killed when dispose() is called?

There seem to be similar issues in other projects:
- https://github.com/IBM/nodejs-itoolkit/pull/272
- https://github.com/mscdex/ssh2/issues/850

Maybe this is a solution? https://github.com/IBM/nodejs-itoolkit/pull/272#issuecomment-621389346

**Comment by coeing** [comment]
@steelbrain Thanks for your quick reaction! I thought it might be a good solution to opening this one as @hagen already created a reproduction example above. I don't have one yet.

**Comment by steelbrain** [comment]
What you're recommending is a nuclear option. `destroy()` severs the connection instead of ending it gracefully. While it may fix your specific case, it may end up being a headache for dozens others. In the short term, if you need a patch to use with your windows servers, try

```js
function disposeSsh(ssh) {
  if (ssh.connection) {
    ssh.connection.on('error', function() { /* No Op */ })
    ssh.dispose()
  }
}
```

**Comment by coeing** [comment]
@steelbrain Yes, it sounds to me like a workaround as well. As the devs at IBM found no other solution for the moment it may be worth a try though :) 

I just tested it for my case and it solved the problem. I will give your workaround a quick try as well.

**Comment by coeing** [comment]
@steelbrain Alright, your workaround works for me as well. I wasn't aware that the connection is available on the NodeSSH object 👍

**Comment by kjcohen** [comment]
@steelbrain Hi -- I am running to the same issue as OP -- I tried using the function you created but still face the same error.

Could you take a look and let see where I am going wrong?

`
function disposeSsh(ssh) {
  if (ssh.connection) {
    ssh.connection.on('error', function() { /* No Op */ })
    ssh.dispose()
  }
}

exports.handler = async (event) => {
  

  const fs = require('fs')
  const path = require('path')
  const {NodeSSH} = require('node-ssh')

  
const ssh = new NodeSSH()
ssh.connect({
  host: host,
  username: user,
  privateKeyPath: secret
})

  let prom = new Promise(function(resolve, reject) {
disposeSsh(ssh);
resolve(1)

  });
  
    const res = await prom;

  var response = {
    statusCode: 200,
    body: [
      {
        'ERROR_CODE': 0,
        'ERROR_MSG': res
      }
      ],
  };
  return response;
  
    
  } catch (err) {
    console.log ('ERROR: ' + err)
    var response = {
    statusCode: 401,
        body: [
      {
        'ERROR_CODE': 401,
        'ERROR_MSG': err
      }
      ],
  };
  return response;
  }



}`
