### ISSUE TITLE
How do I use this library with the tryKeyboard option?

### ISSUE THREAD

**Issue by stringa** [steelbrain/node-ssh#17]

**Comment by steelbrain** [comment]
Can you please try to explain the issue? Your bug report doesn't provide a any information

**Comment by stringa** [comment]
The SSH2 library allows for a tryKeyboard options in the connect options. This is used so we don't have to have passwords in our code. 

If you are using this option, then you must intercept/bind to the 'keyboard-interactive' event so one can start accepting input from the terminal.

http://stackoverflow.com/questions/17459165/unable-to-authenticate-using-nodejs-with-ssh2-module-even-though-manual-ssh-wor

I am trying to do this, but I'm not sure this wrapping library exposes a way for me to handle this case.

**Comment by steelbrain** [comment]
This library is a thin layer of beauty over the `ssh2` APIs, to do advance tasks like that I would recommend you use that library and have a look at sources of this tiny one to perform the tasks that you want to.

With that being said, this library should work with that option, just pass `tryKeyboard ` option in the constructor and bind your events to `ssh_connection.connection` as it points to the underlying SSH2 instance

**Comment by stringa** [comment]
I'm pretty sure connection isn't available until connection is called, which is the problem. you need to bind to it before connect(). I will look at this again.

**Comment by steelbrain** [comment]
the `connect` method provides config as-is to the underlying SSH2 instance, have a look at [`the source`](https://github.com/steelbrain/node-ssh/blob/eadede452af60845f15a01e8e5b3b07069ffea39/Source/SSH.js#L44)

**Comment by stringa** [comment]
totally. nobody is arguing that. The problem is that you need to bind to connection before connect is called. this can't happen without new implementation of connect.

**Comment by steelbrain** [comment]
Oh, I am sorry sir. But you might be confused about the life cycle of the connections, we had to initialize the ssh2 instance in the connect method to overcome a limitation to reconnect the connections which is not supported by design in ssh2.

If you have any other questions, please do not hesitate to ask :)
