### ISSUE TITLE
putFile() How can uploaded files show progress.

### ISSUE THREAD

**Issue by xuliangzhan** [steelbrain/node-ssh#177]
How can uploaded files show progress,
For example, I have a large file that takes a long time to upload, so I hope it can show the progress. What should I do

```javascript
// How should I monitor the progress of uploaded files
ssh.putFile(resolve(`dist.zip`), `${uploadPath}/dist.zip`).then(data => {
  // success
}).catch(e => {
  // error
})
```

**Comment by steelbrain** [comment]
Hi @xuliangzhan 	

This package uses [ssh2](https://github.com/mscdex/ssh2) under the hood, specifically its `fastPut` method. I don't think it supports progress events for transfers :)

**Comment by xuliangzhan** [comment]
It's a great feature if it can be supported

**Comment by EvHaus** [comment]
@steelbrain `fastPut` seems to have a `step` function which gets called every time a part of a file was transferred. Could that be exposed through `node-ssh` somehow?

**Comment by EvHaus** [comment]
`fastPut` supports a step command. So you can do:

```js
ssh.putFile(source, target, undefined, {
    step: (total_transferred, chunk, total) => {
        console.log('Uploaded', total_transferred, 'of', total);
    }
}).then(data => {
  // success
}).catch(e => {
  // error
})
```

**Comment by steelbrain** [comment]
Thanks for sharing @EvHaus 

Also, ideally we'd be passing in `null` instead of undefined, at least in the latest version
