### ISSUE TITLE
Question: Do not throw on stderr outputs warning

### ISSUE THREAD

**Issue by vella-nicholas** [steelbrain/node-ssh#178]
What is the recommended approach so I do not throw errors (promise not fulfilled) on stderr outputs Warning? Can I put `ExecOptions.stream` to `stderr` and then throw from `onStderr()` only when the result contains Error?

**Comment by steelbrain** [comment]
Hi There! :)

Thanks for posting your question, I'm having trouble understanding what you mean. Could you please explain a bit further?

**Comment by vella-nicholas** [comment]
What is the purpose of `ExecOptions.stream` : `stream?: 'stdout' | 'stderr' | 'both'` please?

**Comment by steelbrain** [comment]
Good Question!

When you specify `stream: 'stdout'`, you get stdout, but it throws an error if something is detected on stderr, `stream: 'stderr'` returns the stderr stream but no error is thrown. `stream: 'both'` returns an object from the promise with the signature of `{ stdout: string, stderr: string }`, no error is thrown for stderr output for this option.

Cheers

**Comment by vella-nicholas** [comment]
> stream: 'stderr' returns the stderr stream but no error is thrown

Any output from `stdout` is still return, even setting stream: 'stderr'?

**Comment by StoryScriptAI** [comment]
No, `stdout` is not returned when you specify `stream: 'stderr'`

**Comment by steelbrain** [comment]
Specifying `output: 'stderr'` returns stderr, but stdout is completely ignored

**Comment by vella-nicholas** [comment]
Ok it is very clear, thanks. A more general questions, are warnings written on `stderr`? If yes, does that mean specifying `stream: 'stdout'` will throw an error on warning is returned?

**Comment by steelbrain** [comment]
Warnings from executed programs are written to `stderr`, yes. So specifying `stream: 'stdout'` will throw an error as you mentioned.

**Comment by vella-nicholas** [comment]
In order not to throw errors on warnings is to read the output of `stderr` and handle my own logic. Thank you for your help and support!

**Comment by steelbrain** [comment]
Closing as answered, feel free to continue discussing

**Comment by sul4bh** [comment]
I have `execOptions.stream: 'stderr'` but the `ssh.exec()`promise is getting rejected.

You say, "`stream: 'stderr'` returns the stderr stream but no error is thrown". Does "no error is thrown" mean the promise should be resolved?

**Comment by steelbrain** [comment]
@sul4bh Let me clarify, no error is thrown because of the stdout/stderr output. But there are still other factors that could make it fail, like if the ssh server refuses to run the command or something.

Can you share the contents of the error?

**Comment by sul4bh** [comment]
I verified that the command runs successfully. I am running a docker-compose command and docker-compose writes status messages to stderr: https://github.com/docker/compose/issues/5590.

So what is happening is the status code is 0 but stderr is not empty. I think I saw in the code somewhere that this case is a failure case? (sorry can’t lookup the code right now)

**Comment by steelbrain** [comment]
You can do `stream: 'both'` and it'll not fail for stderr being non empty
