### ISSUE TITLE
not able to make a put of a directory?

### ISSUE THREAD

**Issue by msalvarez** [steelbrain/node-ssh#18]
at first thanks for the work.
I want to use this library to move something downloaded in a raspberry to a server and it can be files or directories, but it fail when i'm trying to make a put of a directory, the error is:
 "{ [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }"
it's not going to be able to make a scp of a directory or is a fail?

**Comment by steelbrain** [comment]
Hi @msalvarez. Unfortunately by design sftp only allows transfer of one file at a time. Though we could create a sugar method that does this for you

**Comment by msalvarez** [comment]
Thanks so much Steelbrain,meanwhile I will use another library for the SCP part . 
I would help you with this sugar method, but my node's skill are really limited.
