### ISSUE TITLE
Can I reuse the location of the past command to execute the next one ?

### ISSUE THREAD

**Issue by cahobaut** [steelbrain/node-ssh#190]
Hello, when I try to execute commands it's like the directory is still the root one. 
`var path, node_ssh, ssh, fs
fs = require('fs')
path = require('path')
node_ssh = require('node-ssh')
ssh = new node_ssh()

ssh.connect({
        host: '1.1.1.1',
        username: 'user',
        password: 'pwd'
}).then(function(){
        ssh.execCommand('cd globaldataPRP').then(function(result) {
                console.log('STDOUT: ' + result.stdout)
                console.log('STDERR: ' + result.stderr)
        }).then(function(){
                ssh.execCommand('ls').then(function(result) {
                        console.log('STDOUT: ' + result.stdout)
                        console.log('STDERR: ' + result.stderr)
                })
        })

});
`
It doesn't show the content of globaldataPRP.
When I try cd `globaldataPRP | ls` it's the same problem it's not Moving into the directory.
Any suggestions ?

**Comment by steelbrain** [comment]
You'll have to use `requestShell` and then interact with it like a shell, commands in a shell will share a session

**Comment by cahobaut** [comment]
So I've to do it with this other Library ? Or is your one based on it ?
I've a more general question, my goal is to connect to a network equipement passing by two or tree bastion then execute commands and then get back results. I've also to store logs of connection. Is that possible with your Library or should I use ssh2shell

**Comment by steelbrain** [comment]
`requestShell` is not another library, it's a function you call on an SSH instance `ssh.requestShell()`, it returns an SSH2.Shell instance, you can read more about how to use it in the parent library's documentation https://github.com/mscdex/ssh2#start-an-interactive-shell-session

**Comment by steelbrain** [comment]
Closing as answered, feel free to continue discussing
