### ISSUE TITLE
ssh.get() parameters are reversed

### ISSUE THREAD

**Issue by cpotemski** [steelbrain/node-ssh#20]
Hey steelbrain,

i noticed that the documentation of the get()-function is reversed.

the FIRST parameter is the local folder and the SECOND is the remote folder

    get(remoteFile, localFile, SFTP) {

as you see here

    SFTP.fastGet(localFile, remoteFile, function(err){

**Comment by steelbrain** [comment]
I did that because it makes the perfect sense to me, you write the path to the file you wanna fetch and then you write where you wanna store it. Also changing it at this point would be breaking compatibility, I won't mind doing this in the next major bump though

**Comment by cpotemski** [comment]
But you have to change it in the method. The param for the remote path is
used on the local machine and vice versa. The order of the params is
correct. It displays the direction of data transfer.

Steel Brain <notifications@github.com> schrieb am Mo., 30. Mai 2016, 20:27:

**Comment by steelbrain** [comment]
I've added this to v3.0.0 milestone btw

**Comment by steelbrain** [comment]
Fixed in v3.0.0

**Comment by cpotemski** [comment]
Nice :) Thank you.

**Comment by steelbrain** [comment]
Just a reminder that there are a lot of API breaking changes in the new release, make sure to read [`CHANGELOG.md`](https://github.com/steelbrain/node-ssh/blob/master/CHANGELOG.md)
