### ISSUE TITLE
Running multiple commands in one connection?

### ISSUE THREAD

**Issue by cfullerton** [steelbrain/node-ssh#201]
I can't use && as it is for a router, I tried putting another ssh.execCommand in the callback of another one and that didn't work.

**Comment by steelbrain** [comment]
You should use `requestShell` if you want to write multiple commands in one-connection, you'll have to read/expect/write to the shell tho

**Comment by millette** [comment]
@cfullerton I've just started using `node-ssh` and this worked well for me:

```js
const myFun = async (host) => {
  const ssh = new SSH()
  try {
    await ssh.connect({
      host,
      username: process.env.SSH_USERNAME,
      passphrase: process.env.SSH_PASSPHRASE,
      privateKey
    })

    const webServers = await ssh.execCommand("grep server_name *", { cwd }).then(webServerFn)
    const cpu = await ssh.execCommand("uptime").then(cpuFn)
}
```

**Comment by steelbrain** [comment]
Closing based on @millette's answer. Thank you
