### ISSUE TITLE
Streams not closing properly

### ISSUE THREAD

**Issue by jldowns** [steelbrain/node-ssh#21]
When chaining many .then() blocks, I get 

```
Error: (SSH) Channel open failure: open failed
```

due to hitting the max number of connections to my remote server. I think this is the same issue as https://github.com/mscdex/ssh2/issues/219 . I added some `.close()` calls before the Promise resolutions and it solved my problem.

I'll submit a pull request with what worked for me, although I don't have any test scripts to run it against.

**Comment by steelbrain** [comment]
Fixed by #22
