### ISSUE TITLE
helpers.js does not suport .ppk keys

### ISSUE THREAD

**Issue by StasAreshin** [steelbrain/node-ssh#260]
This project does not support ssh keys that start with: 'PuTTY-User-Key-File-2'

I suggest replacing this line:
`      if (!(privateKey.includes('BEGIN') && privateKey.includes('KEY'))) {`
to this
`      if (
          !(privateKey.includes('BEGIN') && privateKey.includes('KEY'))
          && !(privateKey.includes('PuTTY-User-Key-File-2'))
      ) {`
in helpers.js

**Comment by steelbrain** [comment]
Have you configured that the underlying `ssh2` supports Putty private keys?

**Comment by StasAreshin** [comment]
I am trying to use `electron-simple-publisher`.
It uses yours project [here](https://github.com/megahertz/electron-simple-publisher/blob/master/src/transport/ssh.js)
With my changes in your helpers and with these settings to publisher:
`{
    "transport": {
        "module": "ssh",
        "host": "hostname",
        "port": xportx,
        "username": "username",
        "privateKeyPath": ".ssh/id_rsa.ppk",
        "remotePath": "/some/path",
        "remoteUrl": "/some/path"
},
"updatesJsonUrl": "http://hostname/some/path/update.json",
    "path": "release"
}`
I was able to upload files. My id_rsa.ppk looks like this: 
`PuTTY-User-Key-File-2: ssh-rsa
Encryption: ....
.....`

The chain of my search was: [ssh2](https://github.com/mscdex/ssh2) -> [ssh2-streams](https://github.com/mscdex/ssh2-streams). electron publisher use the old version of node-ssh (and ssh2-streams of course), But current version also has a parser for these keys:
https://github.com/mscdex/ssh2-streams/blob/master/lib/keyParser.js#L1040

**Comment by StasAreshin** [comment]
Hi, @steelbrain 
I just want to notify you. I already solved my problem by creating my own publisher using the ssh2 package. So, I no longer need the node-ssh package (and this issue).
Thanks for your time.

**Comment by steelbrain** [comment]
@StasAreshin I am glad you were able to take care fo this! Happy for you

I'll prefer to keep the issue open for ppk support in the project

**Comment by steelbrain** [comment]
Fixed in 59015fa2fa509e875757240a39905c8bf642cc08

**Comment by steelbrain** [comment]
Released in v9.0.0
