### ISSUE TITLE
config.privateKey as Buffer does not work

### ISSUE THREAD

**Issue by uNmAnNeR** [steelbrain/node-ssh#267]
from readme:
```
/*
 Or
 ssh.connect({
   host: 'localhost',
   username: 'steel',
   privateKey: fs.readFileSync('/home/steel/.ssh/id_rsa')
 })
 if you want to use the raw string as private key
 */
```
But always get ` Error: config.privateKey must be a string`

**Comment by steelbrain** [comment]
`fs.readFileSync('/home/steel/.ssh/id_rsa')` should be `fs.readFileSync('/home/steel/.ssh/id_rsa', 'utf8')`

Also make sure the path is correct
