### ISSUE TITLE
very need getDirectory :) help please

### ISSUE THREAD

**Issue by timikrutik** [steelbrain/node-ssh#286]
Please, add getDirectory

**Comment by timikrutik** [comment]
I dont know how to copy dir from remote server
Can you help me?

**Comment by steelbrain** [comment]
I'll add it this weekend, please ping if I don't :)

**Comment by steelbrain** [comment]
`getDirectory` added in https://github.com/steelbrain/node-ssh/pull/297

**Comment by steelbrain** [comment]
Released in v9.0.0
