### ISSUE TITLE
getDirectory should unixify server paths

### ISSUE THREAD

**Issue by mbr4477** [steelbrain/node-ssh#300]
Looks like `getDirectory` might need to unixify server paths like `putDirectory` (or provide a configuration option to do so) . My client OS is Windows. I am attempting to get a remote directory from a Linux server and encounter this error:
```
{ Error: No such file
    at SFTPStream._transform (C:\Users\mbr44\Documents\lccgui\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (C:\Users\mbr44\Documents\lccgui\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at SFTPStream.Writable.write (_stream_writable.js:299:11)
    at Channel.ondata (_stream_readable.js:709:20)
    at Channel.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12) code: 2, lang: '' }
```
The remote path I am passing in is
```
/home/<my username>/example/out
```
This directory contains a single test file `out.txt`, and I have verified that it exists at the correct path on the server. Via the `validate` function I passed to `getDirectory` I am noticing that the item path becomes
```
\home\<my username>\example\out\out.txt
```
which I believe is causing the issue since the path separators have been switched to Windows. It might be fixable by changing
https://github.com/steelbrain/node-ssh/blob/21d17b4889d6ec4a53db001ef961ded57032a5f7/src/index.ts#L683-L684
to
```typescript
    const files = scanned.files.map(item => unixifyPath(fsPath.relative(remoteDirectory, item)))
    const directories = scanned.directories.map(item => unixifyPath(fsPath.relative(remoteDirectory, item)))
```

**EDIT: I am using v10.0.0**

**Comment by steelbrain** [comment]
@mbr4477 What version are you on? I've pushed some unixify fixes in v10.0.0

**Comment by mbr4477** [comment]
I am using v10.0.0. Two local changes got it to work. My original thought was incorrect. 

1. Changed
https://github.com/steelbrain/node-ssh/blob/21d17b4889d6ec4a53db001ef961ded57032a5f7/src/index.ts#L658-L681
to add
  ```typescript
  join(pathA, pathB) {
      return fsPath.posix.join(pathA, pathB)
  },
  ```
to the `fileSystem` object to make sure posix separators were used when scanning directories.

2. Changed
https://github.com/steelbrain/node-ssh/blob/21d17b4889d6ec4a53db001ef961ded57032a5f7/src/index.ts#L715
to
```typescript
const remoteFile = fsPath.posix.join(remoteDirectory, file);
```
to make sure posix separators were used when calling `getFile`.

**Comment by steelbrain** [comment]
Thanks for the suggestion, I'll fix the relevant instances

**Comment by steelbrain** [comment]
@mbr4477 Can you please review https://github.com/steelbrain/node-ssh/pull/301?
