### ISSUE TITLE
Connection dies after a few seconds with Nodejs 14

### ISSUE THREAD

**Issue by andrejcremoznik** [steelbrain/node-ssh#303]
This might be an issue with the underlying ssh2 library but there are regressions with nodejs 14.

I have a script that connects and uploads a file to server. Shortly after `putFile` starts the connection dies leaving a partially uploaded file on the server (around 300 KB of a ~20 MB file).

Downgrading to nodejs 13 or 12-lts fixes the issue.

Edit: `node-ssh` version: `10.0.1`

**Comment by steelbrain** [comment]
Thank you for reporting this @andrejcremoznik

Have you tried setting `concurrency: 1` in `transferOptions` in `putFile(...)`? I'm not sure if it would help but worth a try.

**Comment by andrejcremoznik** [comment]
Sorry for the late reply.

Yes, I can confirm that `ssh.putFile('src', 'dest', null, { concurrency: 1 })` works. I this related to the max sessions option in SSH daemon configuration on the server?

**Comment by steelbrain** [comment]
That is correct, yes :)

Closing based on above comment
