### ISSUE TITLE
executeCommand for 'mount' command puts 'stdin' string too early

### ISSUE THREAD

**Issue by serpaulius** [steelbrain/node-ssh#306]
I have encountered a race condition issue using _executeCommand_ like this:
```js
sshConnection.execCommand(`mount -t smbfs //username@some.server/folder /Volumes/mountedFolder`, { stdin: `${pass}\n`, options: {pty: true} })
```
When running this command, the _pass_ variable with password is put into the _stdout_ too early, and when debugging with _onStdout_ handler, the output is similar to:
```
myawesomepassword

Password for some.server: 
```
After that the _executeCommand_ hangs and waits for input.

However, if debugging with a breakpoint on the node-ssh library's `stream.write(options.stdin);`, and after waiting a while, then continuing -- the _stdout_ succeeds on time and the password is placed on time.

Do you have any suggestions or know any workarounds?
Is it possible to execute and wait for some time before entering the password (maybe in a separate command)?

Thank you in advance!

**Comment by steelbrain** [comment]
Hi @serpaulius 

If you want to have to wait before writing your contents to stdin, maybe try `requestShell()` instead of `execCommand()` and listen-for and write back the response with something like [expected-write](https://github.com/steelbrain/expected-write)

**Comment by serpaulius** [comment]
Thank you, that's exactly what I needed, ant it works. :)

But still, I think it would be very useful to have an optional expected string parameter on _executeCommand_ (or even a separate execution method for commands which expect input). There must be a lot of cases, where one assumes, that _stdin_ will be written only when stdin is listened in the executed program -- not instantly submitted after the line execution.

What do you think?
I could try to implement it and make a pull request for you to review, if you see this as a useful addition to the library. :)

**Comment by steelbrain** [comment]
I've got a WIP modern reimplementation of expected-write @ https://github.com/steelbrain/expected-write/pull/1

After it's merged and released, I think we can update node-ssh docs to show some example usage. I disagree on bundling it with this package, as I'd like it to be as lean as possible

**Comment by steelbrain** [comment]
Closing as https://github.com/steelbrain/node-ssh/issues/160 tracks the same issue
