### ISSUE TITLE
Can I use this to create SSH Tunnel

### ISSUE THREAD

**Issue by hckhanh** [steelbrain/node-ssh#308]
I wanna try this library but I don't know whether or not I can create a tunnel with this

**Comment by steelbrain** [comment]
Hi @hckhanh

This library is a wrapper (along with some neat features) around the [`ssh2`](https://github.com/mscdex/ssh2) package.

The underlying package does support `forwardOut` and `forwardIn` for tunneling. See API for more info: https://github.com/mscdex/ssh2#api

You can access the underlying `ssh2` instance on `.connection`, eg:

```
async function main() {
  const ssh = new NodeSSH()
  await ssh.connect(...)
  ssh.connection.forwardOut(...)
}
```

**Comment by hckhanh** [comment]
thank you, now I end up with `node-ssh-forward`
