### ISSUE TITLE
getDirectory() returns files, but they are empty

### ISSUE THREAD

**Issue by FSchieber** [steelbrain/node-ssh#311]
Hello, I'm trying to download some TXT and JSON files from a remote server using the getDirectory(), but they always are downloaded as empty files (0kb).

I have the following code:
```
 ssh.getDirectory('./localfolder/', '/home/remotefolder/').then(function () {
            console.log("The File's contents were successfully downloaded");
        }, function (error) {
            console.log("Something's wrong");
            console.log(error);
        })
```
Also, the callback is never called and I don't get either the success log or any error.

Thanks

**Comment by steelbrain** [comment]
If the callback is never called, then it means the data transfer is not complete yet. So it makes sense that the files would be empty.

If you are experiencing this consistently, try setting a smaller number for `concurrency`

**Comment by steelbrain** [comment]
Concurrency default has now been set to `1`, lmk if you're still experiencing this and I'll reopen
