### ISSUE TITLE
Local hidden files or hidden folders will be ignored

### ISSUE THREAD

**Issue by wakeupfive** [steelbrain/node-ssh#313]
After compiling, I will generate some hidden folders, but they are always ignored and cannot be uploaded to the Linux server.

**Comment by steelbrain** [comment]
Hi @wakeupfive!

That happens because the default `validate()` function ignores all dot-files. You can fix this by specifying a custom `validate` method and allowing your desired dot files in there.

Thanks!

**Comment by pedroricardo** [comment]
@steelbrain

when using putDirectory how can I specify for validate to copy all files including hidden ones like .env

why send me an example?
