### ISSUE TITLE
Support SSH proxies

### ISSUE THREAD

**Issue by nikolay** [steelbrain/node-ssh#32]
http://stackoverflow.com/questions/22174280/emulating-sshs-proxycommand-using-the-node-js-ssh2-module/22178202#22178202

**Comment by nikolay** [comment]
Also, since OpenSSH v7.3, there's a simplified option ProxyJump to do this as well: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts

Given how common the Bastion Host pattern is nowadays, I think this would be a great feature, which is missing in most Node.js packages and everybody needs to implement this manually.

**Comment by steelbrain** [comment]
This package is just a proxy to the `ssh2` module shown in the example, so that example would work fine, you'll just have to use the new promised API instead of the callback one

**Comment by nikolay** [comment]
@steelbrain It surely would, but this is a basic and growing in popularity use case, and it would be of great value to the project to have this matching OpenSSH feature built-in.

**Comment by steelbrain** [comment]
@nikolay I'm sorry I may not have been clear enough, but as I said earlier the first example of the error is already supported :)

**Comment by nikolay** [comment]
@steelbrain I completely understand, and I'm already using it, but my point was to have support regarding adding this as new functionality.

**Comment by niceboyat** [comment]
Yes, I hope so too.
