### ISSUE TITLE
Bug | version 11.0.0

### ISSUE THREAD

**Issue by devseckobz** [steelbrain/node-ssh#324]
I tried to check it in a separate file and run it. but its generating thesame error at all :( 

D:\nodejs\test.js:6
ssh = new NodeSSH()
      ^

TypeError: NodeSSH is not a constructor
    at Object.<anonymous> (D:\nodejs\test.js:6:7)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

------------------------
Sample code 

var path, NodeSSH, ssh, fs

fs = require('fs')
path = require('path')
NodeSSH = require('node-ssh')
ssh = new NodeSSH()

ssh.connect({
  host: 'localhost',
  username: 'steel',
  privateKey: '/home/steel/.ssh/id_rsa'
}).then(() =>{
//do stuff
})

**Comment by steelbrain** [comment]
Sorry about that, fixed docs in https://github.com/steelbrain/node-ssh/commit/103ffc61ffc4d9903f228e4a1b524998806cb4e1

It's a new change in v10, please change the way it's imported in your code
