### ISSUE TITLE
The putFile method is stopping on big files

### ISSUE THREAD

**Issue by SakiiR** [steelbrain/node-ssh#325]
I sent a 7.2 Mb file over SSH through node-ssh and it blocks without completely writing the file.

```js
var SSH2Promise = require("ssh2-promise");

async function main() {
  const ssh = new NodeSSH();

  await ssh.connect({
    host: "[[REDACTED]]",
    username: "[[REDACTED]]",
    privateKey: "[[REDACTED]]",
  });

  console.log("connected!");
  await ssh.putFile("/tmp/test.tar", "/tmp/test.tar");

  await ssh.dispose();
  console.log("disconnected!");
}

main();

```

**Comment by steelbrain** [comment]
Hi @SakiiR 

What version of node-ssh are you on? If you're not on v10, can you set `concurrency` to `1` in your code and try gain?

**Comment by SakiiR** [comment]
Here is my version:

```json
{
    "node-ssh": "^10.0.2",
}
```

Actually, the `concurrency: 1` thing worked ! thank you 👍 

However, do you have any idea why it locks this way ?

Is that because of a concurrency mishandling (deadlock) ?

**Comment by steelbrain** [comment]
Some ssh-servers are really bad at handling concurrency, that could be why.

If you update to v11, concurrency is now `1` by default!
