### ISSUE TITLE
Readme of npm repository is not up to date

### ISSUE THREAD

**Issue by julianpoemp** [steelbrain/node-ssh#333]
I updated to the current version (11.0.0). After I run my code I got the `NodeSSH is not a constructor` error message. I first  read the README on [npm](https://www.npmjs.com/package/node-ssh) but couldn't find the root of the error. But after I looked at the README of this Github repository I found out that a line was changed:

````
const NodeSSH = require('node-ssh');
````
should be

````
const {NodeSSH} = require('node-ssh');
````

Can you update the npm Readme, please?

**Comment by steelbrain** [comment]
Fixed in v11.1.0

Thank you!
