### ISSUE TITLE
only default export is available

### ISSUE THREAD

**Issue by ShroXd** [steelbrain/node-ssh#334]
I'm using `vue-cli` and `electron-builder-vue-cli` to build a electron app. Webpack's version is 4.
I import node-ssh like this:
```
const node_ssh = require("node-ssh");
```

but when i start with `yarn run electron:serve`, something went wrong.
```
error  in ./node_modules/xxx/xxx.mjs
Can't reexport the named export 'XXX' from non EcmaScript module (only default export is available)
```

I had tried this: https://github.com/apollographql/apollo-link-state/issues/302#issuecomment-431219631   but its cant work.

now i using v7.0.0, it seems to work

**Comment by steelbrain** [comment]
Documentation issue in README. It should be `const node_ssh = require("node-ssh").NodeSSH;`

Fixed in v11.1.0

Thank you!
