### ISSUE TITLE
Issue with nodejs v12.18.3 on CentOS 8.2

### ISSUE THREAD

**Issue by vishalsevani** [steelbrain/node-ssh#337]
In my application I open 200 ssh connections in parallel and then execute some commands. 

Iam now migrating to node v12.18.3 on CentOS 8.2. With node v12.18.3, all the ssh connections fail with error message as "Timed out while waiting for handshake" and node process hogs 100% CPU all the time. However the same code works fine with node v12.0.0 on CentOS 8.2. Infact the same code even works on nodejs v12.18.3 but on Ubuntu 20.04. So issue seems to be combination of nodejs v12.18.3 and CentOS 8.2.

I wrote a stand-alone nodejs code to replicate the issue and I was able to. The code is

```javascript
const {NodeSSH} = require('node-ssh'); 

async function getSSHConn(ip) {
    const options = {
      host: ip,
      username: 'ubnt',
      readyTimeout: 10000,
      algorithms: {
         kex: ['diffie-hellman-group1-sha1'],
         cipher: ['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', '3des-cbc', 'aes256-cbc']
      }
    };
    let sshConn;
    const passwords = ['abc1','abc2','abc3'];
    const sshConnection = new NodeSSH();
    for (let i = 0; i < passwords.length; i += 1) {
      options.password = passwords[i];
      try {
        sshConn = await sshConnection.connect(options);
        break;
      } catch (error) {
        console.log('error ' + error.message);
        sshConnection.dispose();
      }
    }
    if (sshConn) {
      console.log('success ' + ip);
      sshConnection.dispose();
    } else {
      console.log('fail ' + ip);
    }
  }

const ips = [200 unique ips];
for (var i = 0; i < ips.length; i ++) {
        getSSHConn(ips[i]);
}
```

This sample code runs fine with node 12.0.0 on CentOS 8.2, but fails with node v12.18.3. 

Note that I have taken readyTimeout as 10 secs. If I keep the readyTimeout as 50 secs, it works on nodejs 12.18.3 as well. However it takes about 40 secs to complete and node process hogs 100% CPU all the time. On nodejs v12.0.0 the program takes barely 10 seconds to complete and node doesn't hog CPU. Also in my production application even with timeout of 50 seconds, I could not make it work.   

If you want me to debug further, plz let me know.

**Comment by steelbrain** [comment]
Hello @vishalsevani

Thank you for the detailed error report. This package is a wrapper that gives a nicer API to the underlying `ssh2`, which is where the actual ssh protocol stuff happens.

Please report this to https://github.com/mscdex/ssh2 with a minimal repro code
