### ISSUE TITLE
How does streaming work?

### ISSUE THREAD

**Issue by live-smart** [steelbrain/node-ssh#35]
The example on readme doesn't seem to work. The code in then clause is never executed.

**Comment by steelbrain** [comment]
Hi @live-smart, I don't know which API you are referring to. There's no streaming APIs provided by this library IIRC.

Can you explain it a bit more?

**Comment by live-smart** [comment]
For example, when I fire a long running command, I hope to see stdout streamed to me over time, instead of sent back one off on execution complete.

**Comment by live-smart** [comment]
`tail -f xxxx` for example

**Comment by live-smart** [comment]
You do have

```
  // Command with escaped params
  ssh.exec('hh_client', ['--json'], { cwd: '/var/www', stream: 'stdout' }).then(function(result) {
    console.log('STDOUT: ' + result)
  })
```

in readme and that's why I thought it supports this kind of scenario.

**Comment by steelbrain** [comment]
The current APIs do not support streaming (because that's what this wrapper is for). If you want to use streaming, you can use the underlying [`SSH2`](https://github.com/mscdex/ssh2) instance in `ssh.connection`

**Comment by live-smart** [comment]
That's a great hint. Thanks!

**Comment by steelbrain** [comment]
Closing as off-topic, but feel free to continue discussing
