### ISSUE TITLE
Inconsistence in README.md?

### ISSUE THREAD

**Issue by scippio** [steelbrain/node-ssh#36]
I searched for Remote -> Local example... and found:

On npm project page I see:
```
// Local, Remote 
ssh.getFile('/home/steel/Lab/RemoteSource', '/home/steel/Lab/LocalTarget')
```
but on github:
```
// Local, Remote
ssh.getFile('/home/steel/Lab/localPath', '/home/steel/Lab/remotePath')
```

**Comment by steelbrain** [comment]
This is a docs outdated issue that'll be automatically fixed when a new version is published
