### ISSUE TITLE
getDirectory() feature

### ISSUE THREAD

**Issue by scippio** [steelbrain/node-ssh#37]
It would be nice to have it :)

**Comment by steelbrain** [comment]
Yes, it certainly would be nice to have this feature :)

Until it's implemented though, you can use exec to convert a directory into a tar, then download that directory and extract it locally.

**Comment by fergomez** [comment]
Hello, any plans to include this in the library soon? Any suggestion on how to implement it with this library, otherwise? Thanks.

**Comment by steelbrain** [comment]
@fergomez Not the highest on my priority list, but eventually :)

**Comment by steelbrain** [comment]
Added in https://github.com/steelbrain/node-ssh/pull/297

**Comment by steelbrain** [comment]
Released in v9.0.0
