### ISSUE TITLE
putFile stucks for files > 1.8MB

### ISSUE THREAD

**Issue by Gappa88** [steelbrain/node-ssh#384]
it happens that `putFile `freezes if I try to send a file greater then 1.8MB (2000 rows).

**Node v14.15.0
node-ssh 11.1.1**

code snippet:
```

'use strict';
const { NodeSSH } = require('node-ssh');
async function uploadFile(filename, filePath) {
 
    let server = servers_to_send_files[0];
    let ssh = new NodeSSH();
    try {
        await ssh.connect({
            host: server.host,
            username: server.username,
            privateKey: server.privateKey
        });
        await ssh_put_file (ssh, filename, filePath);

    } catch (e) {
        logger.error(e);
    }

    ssh.dispose();
    return;
}

async function ssh_put_file(ssh, filename, filePath) {
    const ret = await ssh.putFile(filePath + filename, '/newpath/' + filename);
     console.log("finished", ret);
    return ret;
}
```

I can't reach the `console.log("finished", ret);`

is there any options to activate or something else?

thanks

**Comment by steelbrain** [comment]
This package is just a wrapper around https://github.com/mscdex/ssh2

Can you change your code to use that package directly and see if you still get the error?

**Comment by Gappa88** [comment]
@steelbrain we solve the problem lowering down (a lot) the `chunkSize`.

could you try to give a motivation for this behaviour? of course you don't have any idea of the environment but just for curiosity try to say the first two things that came to your mind as the reason to this behaviour.

anyway we have 2 servers with ubuntu 18.04 installed on them and both upload files to 3 different machines with the same configuration between them 3 and ubuntu 18.04 installe on them.

thanks

**Comment by Gappa88** [comment]
@steelbrain 
found the problem: we are using node v14. SSH2 has an issue that stops to upload/download files. 
They suggest to use node < v14
