### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by Chizz3x** [steelbrain/node-ssh#409]
Just tried to use node-ssh and it seems like something is wrong with authentication since the details that I am providing are 100% right.

```
await ssh.connect({
    host: 'myHost', // to not expose my host xd
    username: 'root',
    passphrase: 'myPass', // my actual pass for the private key
    privateKey: 'C:/Users/drebu/theKeyFile'
  })
```

I tried connecting with the same settings through Zoc terminal and it all works just fine, but now through node-ssh. I feel like I am doing something wrong here but can't quite understand what exactly.

**Comment by steelbrain** [comment]
Hi @Chizz3x

I see you closed this issue, were you able to resolve it? If so, What worked for you?

**Comment by Chizz3x** [comment]
> Hi @Chizz3x
> 
> I see you closed this issue, were you able to resolve it? If so, What worked for you?

Seems like I was just using the wrong private key, nothing too interesting
