### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by gajus** [steelbrain/node-ssh#424]
Constantly getting error:

```
Error: Timed out while waiting for handshake
  at Timeout._onTimeout (/Users/gajus/Documents/dev/contra/contra-manager/node_modules/ssh2/lib/client.js:1014:23)
  at listOnTimeout (node:internal/timers:557:17)
  at processTimers (node:internal/timers:500:7)
```

The script is simply:

```ts
const ssh = new NodeSSH();

await ssh.connect({
  host,
  privateKey: temporaryKeys.privateKey,
  username: temporaryKeys.username,
});
```

Is there a configuration I am missing?

**Comment by steelbrain** [comment]
Have you tried connecting through regular SSH client? The error you're experiencing is a network error, and generally means the destination host is not reachable. If you can connect with the regular ssh client, but failing to be able to, with node-ssh then please let me know!

**Comment by steelbrain** [comment]
`node-ssh` pipes the connection options to ssh2 (https://github.com/mscdex/ssh2#client-methods). I think you can use the `readyTimeout` option to potentially increase the timeout limit.

Good luck!
