### ISSUE TITLE
How about method ssh.disconnect ?

### ISSUE THREAD

**Issue by naliferov** [steelbrain/node-ssh#447]

**Comment by naliferov** [comment]
Ofcourse there is ssh.getConnection().end();

**Comment by Spoki4** [comment]
You can try: `dispose` method. It would do what you want.
```ts
dispose(): void {
  if (this.connection) {
    this.connection.end()
    this.connection = null
  }
}
```

**Comment by steelbrain** [comment]
Closing based on above comment. Thanks @Spoki4 .

Please feel free to continue discussing. Will reopen discussion if there's more things to be discussed
