### ISSUE TITLE
Handle retries properly

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/node-ssh#46]
There are times when we have to wait for the `continue` event before sending more traffic, not urgent but good to have

**Comment by alancwoo** [comment]
Actually I had a quick question about this - am wondering if it's related to this subject. I'm using node-ssh to upload changed files. However, I'm finding it fails constantly if it tries to upload too many files at once.

Is there a better way to keep the connection alive/open and just upload each file as they change?

I'm often getting issues like `AssertionError: Not connected to server`, `protocol error: rcvd type 90`, `Protocol error: expected packet type 21, got 90`

**Comment by steelbrain** [comment]
Yes @alancwoo.

You can upload the files one at once or even five at once by chaining/using promises properly. If you use the builtin `putFiles` or `putDirectory` instead of `putFile` though, you should get a much better experience with large number of files

**Comment by steelbrain** [comment]
Also I've published `maxAtOnce` support in `putFiles` in node-ssh@3.2

**Comment by steelbrain** [comment]
The concurrency option in latest release fixes this
