### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by zydingjun** [steelbrain/node-ssh#468]
1# add function ssh.close() to close the SSH session;
2# add ConnectTimeout limit for configure;

**Comment by steelbrain** [comment]
Hi @zydingjun!

Thanks for writing in. For closing the ssh connection, you can just call `ssh.dispose()`

The timeout is an already supported option, please see [`readyTimeout`](https://github.com/mscdex/ssh2/#:~:text=Default%3A%20(none)-,readyTimeout,-%2D%20integer%20%2D%20How) in ssh2 config. You can use it with `node-ssh` in `.connect()` so it would look like `ssh.connect({ ... , readyTimeout: 20000})`

Closing this issue as the question has been answered but feel free to continue discussing.
