### ISSUE TITLE
Encrypted private keys?

### ISSUE THREAD

**Issue by alancwoo** [steelbrain/node-ssh#47]
I'm getting an error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Encrypted private key detected, but no passphrase given` but not sure if I've missed a way to prompt for or define the passphrase?

**Comment by steelbrain** [comment]
Hi @alancwoo You can pass in the passphrase into the same object that you feed private key path. Let me know if you still have the issue

**Comment by alancwoo** [comment]
OK this wors perfectly! Maybe a note in the readme would be beneficial? I couldn't even find the word `passphrase` in the source? Also, in case it helps anyone, even if the key is unlocked with `ssh-agent`, some form of a passphrase (even if gibberish) allows the connection to carry on successfully.

**Comment by steelbrain** [comment]
@alancwoo It's not documented in the README because this package does not directly process any of these options (except `privateKey`), it only passes them on to `ssh2` and link to that package is given in README
