### ISSUE TITLE
getFiles() documentation wrong

### ISSUE THREAD

**Issue by nickolasclarke** [steelbrain/node-ssh#53]
it should be: `getFile('/path/to/remote', 'path/to/local')`

**Comment by steelbrain** [comment]
Hi @nickolasclarke!

We actually don't have a `getFiles()` at all yet, can you tell me where you saw the docs for `getFiles()`?

**Comment by nickolasclarke** [comment]
@steelbrain welp I've screwed this all up. its `getFile()` not `getFiles()` and in my PR changed the documentation for `putFile()` not `getFile()`. Let me fix that. . .

**Comment by steelbrain** [comment]
Fixed in master, as discussed in #54
