### ISSUE TITLE
putDirectory fails with no such file recursively

### ISSUE THREAD

**Issue by drewlsvern** [steelbrain/node-ssh#59]
When I try to use the function ssh.putDirectory() and transfer an entire directory and its files recursively, it transfers all the directories correctly but fails to transfer any files. I receive an error

 { [Error: No such file] code: 2, lang: '' }

If I set recursive to false then it transfers the one file in the base directory just fine. Please advise. I am using the example provided.

Thanks.

**Comment by steelbrain** [comment]
Hi @drewlsvern, that's an interesting error you got there. Can you tell me which operating system you are on? and if you could prepare an isolated piece of code along with some files that'll help me repro the bug would be amazing

**Comment by drewlsvern** [comment]
Hi @steelbrain. I'm running on Ubuntu 16.04 on both systems(local and remote). I'll make a quick nodejs example and post a link shortly.

**Comment by drewlsvern** [comment]
Here is an example.
[node-ssh-put-ex.tar.gz](https://github.com/steelbrain/node-ssh/files/731172/node-ssh-put-ex.tar.gz)

**Comment by steelbrain** [comment]
I can repro the error successfully, investigating

**Comment by steelbrain** [comment]
Turns out we had a spec who was failing but I wasn't paying attention to, this has been fixed in https://github.com/steelbrain/node-ssh/pull/60 and released in v4.0.1

**Comment by drewlsvern** [comment]
Beauty, confirmed working!
