### ISSUE TITLE
Example on how to end a connection

### ISSUE THREAD

**Issue by caneta** [steelbrain/node-ssh#61]
Copy/pasting the example in the readme.md, the connection is not closed at the end of the process, could you please give an example?
I saw [this thread](http://stackoverflow.com/questions/30392921/how-to-disconnect-ssh-connection-by-using-node-ssh-in-node-js) about the end() method, but it does not work to me.
It gives me `TypeError: ssh.end is not a function`.
Thank you.

**Comment by Radobilly** [comment]
`ssh.dispose()` closes the connection

**Comment by caneta** [comment]
Ok, thanks.
A minimal working example follows:
```
'use strict';
const node_ssh = require('node-ssh');
const ssh = new node_ssh();

ssh.connect({
  host: 'my.remote.host',
  username: 'user',
  privateKey : '/home/user/.ssh/id_rsa'
})
.then(function() {
  ssh.putDirectory('dist/', '/my/remote/path/', {})
  .then(function() {
    console.log('Directory transfer was successful');
    ssh.dispose();
  })
  .catch(function(error){
    console.log('putDirectory error');
    console.log(error);
    ssh.dispose();
  });
})
.catch(function(error){
  console.log('ssh connection error');
  console.log(error);
});
```

**Comment by steelbrain** [comment]
Thanks @Radobilly for the quick answer.
@caneta he's correct, `.dispose()` disposes the connection, that and more docs are available in the [API section of README](https://github.com/steelbrain/node-ssh#api)

Closing as answered but feel free to continue discussing
