### ISSUE TITLE
Can you use exec or execCommand to run a bash script?

### ISSUE THREAD

**Issue by dopyoman** [steelbrain/node-ssh#62]
Im trying to upload a bash file to the server and then would like to execute it. would it be possible to do so and stream the output back?

I been messing around with the lib and tried both exec and execCommand
```js
ssh.exec('bash provision.sh', {cwd: '/var/deployer', stream: 'stdout'})
                        .then(result => {
                            ErrorHandler.instance.info(result);
                            ssh.dispose();
                        })
                        .catch(error => {
                            ErrorHandler.instance.error('Somthing went wrong with provisioning \n' + error)
                        })
```
Error i get
```
[Wed Feb 01 2017 18:17:52 GMT+0200 (FLE Standard Time)] ERROR Somthing went wrong with provisioning 
TypeError: a.forEach is not a function
```

```js
                    ssh.execCommand('bash provision.sh', {cwd: '/var/deployer', stream: 'stdout'})
                        .then(result => {
                            ErrorHandler.instance.info(result);
                            ssh.dispose();
                        })
                        .catch(error => {
                            ErrorHandler.instance.error('Somthing went wrong with provisioning \n' + error)
                        })
                })
```

Error
```
signal: undefined,
  stdout: 'Reading package lists...\nBuilding dependency tree...\nReading state information...\ndeb http://packages.blackfire.io/debian any main\nExecuting: /tmp/tmp.YR346mP862/gpg.1.sh --recv-keys\n--keyserver\nhkp://keyserver.ubuntu.com:80\n0xcbcb082a1bb943db\r\nReading package lists...\nBuilding dependency tree...\
````

**Comment by steelbrain** [comment]
Hi @dopyoman 

The bash script as you can see from the output is executed correctly. If I had to guess the error is somewhere in the `errorHandler.instance.info` so try removing that and see if you still get the error

**Comment by dopyoman** [comment]
After a bit of testing it seems like its some kind of encoding problem. The local machine is a windows pc and when its transfered i guess the texts isnt converted. You can see when you open the transferred file in nano


[image](http://i.imgur.com/vC2nr3i.png)

So not sure if you want to close this

**Comment by steelbrain** [comment]
I highly doubt it's a file encoding issue, files with CRLF line separator work perfectly in bash.

```js
doSomething().then(function(result) {
  console.log('result', result)
}).catch(function(error) {
  console.log('error', error)
})
```

If we read it at first it'll look as if

1. then callback is triggered when the promise is resolved
2. catch callback is triggered when promise is rejected

when in reality

1. then callback is triggered when promise resolved
2. catch callback is triggered when promise is rejected OR the then callback throws an error

so what I was suggesting is that the issue might not be in bash execution at all but the logger that you invoke inside then callback

**Comment by dopyoman** [comment]
So you're saying that the logger is throwing an error and it interupts before the promise is resolved?

**Comment by steelbrain** [comment]
Yes, that is very much likely

**Comment by dopyoman** [comment]
Hey I'm going to close this since I've tested this quite a bit and by stripping out the empty line breaks that windows adds I was able to execute the scripts

**Comment by axago** [comment]
it's old but i got the same problem today, to fix it you need to add and array of arguments : 

ssh.exec('bash provision.sh', [], {cwd: '/var/deployer', stream: 'stdout'})
