### ISSUE TITLE
Support for pty?

### ISSUE THREAD

**Issue by CoreyJ87** [steelbrain/node-ssh#73]
I have a couple different bash script I'm running from a lambda function for an alexa skill. One of which requires pty. I didnt see any option to enable it. Is this something that can be added easily? Thanks this lib was majorly helpful

**Comment by steelbrain** [comment]
Thanks for the request, opening a PR in a few mins

**Comment by steelbrain** [comment]
Published and updated README with pty usage 🎉

**Comment by CoreyJ87** [comment]
Awesome thanks for the quick feature addition. Really appreciate it
