### ISSUE TITLE
Get full path in shell

### ISSUE THREAD

**Issue by notmedia** [steelbrain/node-ssh#81]
Hello, have a problem, how I can get the full path in shell?

```js
ssh.connect(sshConfig).then(() => {
  ssh.requestShell().then((stream) => {
    const stdin = process.openStdin();

    stdin.addListener('data', data => {
      //need to know full path here

      // Trim input to prevent the endings of lines in Windows ('\r\n\')
        stream.write(data.toString().trim() + '\n');
    });

    stream.on('data', data => {
      process.stdout.write(data);
    }).stderr.on('data', data => {
      process.stdout.write(data);
    });
  });
});
```

**Comment by steelbrain** [comment]
Hi @notmedia, You can use the `pwd` command to get the current working directory of the shell. Kinda like

```js
async function myVeryCoolAsyncFunction() {
  await ssh.connect(sshConfig)
  const defaultDirectory = await ssh.exec('pwd', [], { stream: 'stdout' })
  const shellStream = await ssh.requestShell()

  const stdin = process.openStdin();
  stdin.addListener('data', (data) => {
    console.log('current path is', defaultDirectory)  
    // Trim input to prevent the endings of lines in Windows ('\r\n\')
    shellStream.write(data.toString().trim() + '\n')
  })
  shellStream.on('data', (data) => {
    process.stdout.write(data)
  })
  shellStream.stderr.on('data', (data) => {
    process.stdout.write(data)
  })
}
myVeryCoolAsyncFunction().then(function() {
  console.log('all done')
}).catch(function(error) {
  console.log('encountered an error', error)
})
```

**Comment by notmedia** [comment]
@steelbrain Thank you for the fast reply. But how can I get a full path from the current dir?
I mean, the program starts in `/root` and then using shell I go to `/home/some/path/to/the/file`. After that, I want to know this path where I entered by the shell.

I need this path for download the file from entered directory without full path to it.

**Comment by steelbrain** [comment]
Hi @notmedia 

In that case, you can just use the `PS1` Variable

<img src="https://cloud.githubusercontent.com/assets/4278113/25304359/0f5b6e56-277f-11e7-9ffb-b4c4a081c522.png">

You just have to make sure to execute `export PS1="\$PWD >>> "` or something similar that includes the escaped `$PWD` variable inside PS1

**Comment by notmedia** [comment]
Thank you @steelbrain 👍
