### ISSUE TITLE
Streaming stdout/stderr for long-running commands

### ISSUE THREAD

**Issue by herchu** [steelbrain/node-ssh#85]
The current exec() call only calls a callback function when the command is done, providing the entire console output as a buffer.

It would be nice to have an alternative call where one can receive output as it is produced, while the command takes long to finish (specially if it is writing its progress to stdout!). 

Currently I am using this on a project, and had to switch to [ssh2](https://github.com/mscdex/ssh2) for this part -- but I like the promises approach more, so would like to keep using node-ssh.

**Comment by steelbrain** [comment]
Sounds fair, thanks for the request

**Comment by sheerun** [comment]
I also need it +1

**Comment by martinlevesque** [comment]
I was also interested to have streaming support.

Did a quick change for my needs - https://github.com/martinlevesque/node-ssh/commit/dbfc33a456bf7690f15c228e7af9150f94b48fc4

**Comment by steelbrain** [comment]
Thanks for the patch @martinlevesque 

I've pushed streaming callbacks support for both `exec` and `execCommand` in master, please upgrade to v5
