### ISSUE TITLE
ssh.dispose should be a promise?

### ISSUE THREAD

**Issue by KhaledMohamedP** [steelbrain/node-ssh#87]
Trying to build a script in top of this cool module, but was surprise why `.dispose()` was not wrap into a promise?

just to keep it align with the other api methods, what you think?

**Comment by steelbrain** [comment]
Hi @KhaledMohamedP 

This is a limitation carried over from the node.js core APIs. The [`socket.end`](https://nodejs.org/api/net.html#net_socket_end_data_encoding) does not accept a callback
