### ISSUE TITLE
Missing end() wrapper

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [steelbrain/node-ssh#9]
From what i see it's actually impossible to close a connection because you can't access the end() method of the underlying ssh2 connection object.

**Comment by steelbrain** [comment]
__Note:__ If anything of the ssh2 object is not implemented and I am taking more time than I should, You can always use `MySSH.Connection.close()`

**Comment by Darynh** [comment]
Maybe add a "@Connected->false" when using end() ? Supposing that Connection.end() is sync.

**Comment by steelbrain** [comment]
@Darynh thanks for your suggestion, I just published an update where you can connect and disconnect as many times as you like on a single instance.

**Comment by DaniGuardiola** [comment]
Was this reverted? I get an `end is not a function` error and I need to use `ssh.connection.end` instead

**Comment by steelbrain** [comment]
@DaniGuardiola It was renamed to `.dispose()`

**Comment by johnosbb** [comment]
I use the dispose() method, but the process using ssh-node will not terminate.
"why-is-node-running" shows 9 handle(s) keeping the process running including:

/home/developer/ApplianceAutomation/AutomationNodejs/node_modules/ssh2/lib/client.js:1012       - this._readyTimeout = setTimeout(() => {
/home/developer/ApplianceAutomation/AutomationNodejs/node_modules/ssh2/lib/client.js:1029       - startTimeout();
/home/developer/ApplianceAutomation/AutomationNodejs/node_modules/ssh2/lib/client.js:1042       - doConnect();
/home/developer/ApplianceAutomation/AutomationNodejs/node_modules/node-ssh/lib/cjs/index.js:194 - connection.connect(config);
