### ISSUE TITLE
possibility to run sudo commands

### ISSUE THREAD

**Issue by solancer** [steelbrain/node-ssh#90]
Is it possible to run sudo commands? sending in password to the pty?

**Comment by steelbrain** [comment]
Hi @solancer 

You can either use a pty to send the password or you can provide the password in stdin to `exec`/`execCommand` for example

```js
ssh.exec('sudo', ['ls /'], { stdin: 'mypassword\n' })
```

`\n` is important after the password

**Comment by solancer** [comment]
That worked like a charm, thanks for taking time to develop such an awesome lib. If you ever come down to Bangalore beer's on me mate ;)

**Comment by steelbrain** [comment]
Thanks for the offer, glad you like it :)

**Comment by SlavikVostretsov** [comment]
Hi @steelbrain 
I've tried your suggestion, however, I got "sudo: no tty present and no askpass program specified" error
What have I done wrong?

**Comment by steelbrain** [comment]
@SlavikVostretsov You have to pass `pty: true` in `ExecOptions.options` so it looks something like

```js
ssh.exec('sudo', ['ls /'], { stdin: 'mypassword\n', pty: true })
```

**Comment by SlavikVostretsov** [comment]
@steelbrain  Still got the same error :(

**Comment by steelbrain** [comment]
@SlavikVostretsov In that case, it's an ssh server config issue.

Try googling with that error message to see if that helps

**Comment by ewnd9** [comment]
There's a typo, `pty` should in the `options` property

```js
ssh.exec("sudo", ["mv file /home/path/"], { options: { pty: true }, stdin: "mypass\n" } )
```

**Comment by syedhabib53** [comment]
As of now for version `10.0.2`, the above solution is not working. Since changes in `options` keyword as `execOptions`. Below is working for me.
```bash
ssh.exec("sudo", ["mv file /home/path/"], { execOptions: { pty: true }, stdin: "mypass\n" } )
```

**Comment by larrybg** [comment]
I have tried this with `execOptions` and `stdin` as the password and still getting back the prompt to enter admin's password.

        ssh.exec("sudo", ["useradd -m -s /bin/rbash userID"],
            {
                execOptions: { pty: true }, stdin: "useradmin_password\n",
                onStdout(chunk) {
                    console.log(`STDOUT: ${chunk.toString('utf8')}`);
                },
                onStderr(chunk) {
                    console.log(`STDERR: ${chunk.toString('utf8')}`);
                    ssh.getConnection().end();
                }
            });

The response is:
`STDOUT: [sudo] password for useradmin:`
