### ISSUE TITLE
putDirectory function fails to create remote folders if empty 

### ISSUE THREAD

**Issue by fergomez** [steelbrain/node-ssh#91]
Hello,

I'm using this library to copy directories from a local environment (using angular2 + Electron) to a remote server. It works really well when I use the "putDirectory" function if I have a directory with folders and files in them, but fails to copy empty folders, no matter where it's stored. If a folder contains an empty folder, this parent folder is not created either. Why is this happening? Thank you.

Cheers.

**Comment by steelbrain** [comment]
Overlooked that part 😄 
Will fix

**Comment by steelbrain** [comment]
Fixed in https://github.com/steelbrain/node-ssh/pull/93
