### ISSUE TITLE
How to switch to root user

### ISSUE THREAD

**Issue by hariaakash** [steelbrain/node-ssh#97]
When I do sudo -i and then trying to execute commands, it's not working. It just stops executing then after

**Comment by jakkor** [comment]
You can do that with SSH2Shell

```
async function run() {
      const node_ssh = requireNode('node-ssh')
      let ssh = new node_ssh()

      await ssh.connect({
        host: [Host],
        username: [Username],
        password: [Password]
      });

      let shellStream = await ssh.requestShell();

      shellStream.on('data', (data) => {
        let stringData = data.toString().trim();
        if (stringData === "[sudo] password for root:") {
          let pass = "[Password]\n";
          shellStream.write(pass);
        }
      });

      shellStream.stderr.on('data', (data) => {
        console.log(data);
      });
      shellStream.write("sudo -i\n");
 }
```

**Comment by steelbrain** [comment]
Thanks @jakkor for taking care of this!

**Comment by hariaakash** [comment]
@steelbrain is there any possibility with node-ssh itself ?

**Comment by steelbrain** [comment]
@hariaakash You can do `ssh.exec('sudo', ['node', '-e', '"console.log(process.time())"'], { stdin: 'myrootpassword\n' })` and it should work fine, presuming the ssh server has been configured correctly (default ubuntu config is good)

**Comment by RohitRane** [comment]
> You can do that with SSH2Shell
> 
> ```
> async function run() {
>       const node_ssh = requireNode('node-ssh')
>       let ssh = new node_ssh()
> 
>       await ssh.connect({
>         host: [Host],
>         username: [Username],
>         password: [Password]
>       });
> 
>       let shellStream = await ssh.requestShell();
> 
>       shellStream.on('data', (data) => {
>         let stringData = data.toString().trim();
>         if (stringData === "[sudo] password for root:") {
>           let pass = "[Password]\n";
>           shellStream.write(pass);
>         }
>       });
> 
>       shellStream.stderr.on('data', (data) => {
>         console.log(data);
>       });
>       shellStream.write("sudo -i\n");
>  }
> ```

Please add this in the main documentation. There is only one line mention of requestShell in both the Github ReadMe as well as the npmjs.com page. 

This is a very useful feature. But documentation doesn't provide enough detail on how to use requestShell & shellStream.
