### ISSUE TITLE
Execute command with input

### ISSUE THREAD

**Issue by theunreal** [steelbrain/node-ssh#99]
When I access my device through SSH I need to enable it. Enabling it takes 2 steps:

- executing "en"
- the command line requests an input
- the input should be "lab"

This is what I tried to do:

```
ssh.connect({
        host: 'my-host',
        username: 'test',
        password: 'test123'
    }).then(function(result1) {
        console.log('Connected!');
        console.log('Executing "en"');
        console.log('STDOUT: ' + result1.stdout)
        console.log('STDERR: ' + result1.stderr)
        ssh.exec('en').then(function(result2) {
            console.log('Executing "lab"');
            console.log('STDOUT: ' + result2.stdout);
            console.log('STDERR: ' + result2.stderr);
            ssh.execCommand('lab').then((function(result3) {
                    console.log('Lab Executed!');
                    console.log('STDOUT: ' + result3.stdout)
                    console.log('STDERR: ' + result3.stderr)
                }
            ));
        }, function (error) {
            res.send('Error');
        })
    })
```

in Putty the command are working (see screenshot)

![image](https://user-images.githubusercontent.com/6171883/33135824-34b6460a-cfac-11e7-8011-aa8c9a44f1d4.png)

In my NodeJS app I get the following console output:

```
Example app listening on port 3000!
Connected!
Executing "en"
STDOUT: undefined
STDERR: undefined
Executing "lab"
STDOUT: undefined
STDERR: undefined
(node:18252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: write ECONNABORTED
```

Any idea what I'm missing?

**Comment by steelbrain** [comment]
`exec` by default only ever returns stdout, so you're actually accessing `str.stdout` and `str.stderr`. If you want to access both, you can either execute `execCommand` directly or pass `{ stream: 'both' }` to `exec` as second parameter so it would look something like

```
ssh.exec('ls', { stream: 'both' }).then(function(output) {
  console.log(output.stdout)
  console.error(output.stderr)
})
```

Closing as answered but feel free to continue discussing

**Comment by theunreal** [comment]
Thanks @steelbrain !
so I solved this but I am facing another issue now, 
seems like I can't exec the password which is "lab", I alwyays get timeout and auth fail.
Screenshot above demonstrate how it suppose to behave (typing "en" then the password - "lab" as input)

```
Connected!
Executing "en"

Password:
% Password:  timeout expired!
% Error in authentication.
Executing "lab"
(node:2672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: No response from server

code:

ssh.connect({
        host: 'my-host',
        username: 'test',
        password: 'test123'
    }).then(function (result1) {
        console.log('Connected!');
        console.log('Executing "en"');
        ssh.execCommand('en').then(function (enable) {
            console.log(enable.stderr);
            console.log(enable.stdout);
            console.log('Executing "lab"');
            ssh.execCommand('lab').then(function (lab) {
                console.log('Executing "dir"');
                ssh.execCommand('dir').then(function (result2) {
                    console.log(result2.stderr);
                    console.log(result2.stdout);
                    res.send(result2.stderr);
                });
            });
        })
```

**Comment by steelbrain** [comment]
If the lab command requires password to execute, you could send it through stdin like `{ stdin: 'mypassword\n' }` to the lab command exec

**Comment by theunreal** [comment]
@steelbrain The password is lab.
After I connect to the device I need to enable it using the "en" command. the "en" command shows a password input where I need to place "lab" there.
only then I can execute "dir" to see the file listing.

Currently, this is what I'm doing, but I get 

> Error: No response from server 

when I'm trying to execute "dir":

```
ssh.execCommand('en, { stidin: 'lab'}).then(function(result) {
    ssh.execCommand('dir').then(function(result2) {
         console.log('dir worked!')l
});
});
```
